@token=eyJhbGciOiJIUzI1NiJ9.NjAyOTJmNjhmODIxNTQzMDliNmUzMjdj.wfeimbo5-3yDQXiXw5LBK2BOO0O8Bfquah-d-bggcLY
@email=test2@gmail.com
@password=test2
###

POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###

POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###

GET http://localhost:5000/api/user/auth
Authorization: Bearer {{token}}

###

GET http://localhost:5000/api/user/posts
Authorization: Bearer {{token}}


GET http://localhost:5000/api/posts

###

GET http://localhost:5000/api/posts/5f0ac8eeb58fc5082367719e
Authorization: Bearer {{token}}
###

DELETE http://localhost:5000/api/posts/5f093f95e982690b555465db
Authorization: Bearer {{token}}